### ISSUE TITLE
Feature request: enum validators, type shortcuts and multiple custom validators

### ISSUE THREAD

**Issue by mikidep** [trenskow/isvalid#10]
First of all I love that you implemented my request for custom validators alongside object schemas! I would like to point out another couple of rough edges I ran into while using isvalid:
### Enum validators
It would be nice to have *enum validators* that compare the value to a list of acceptable values, something like this:
```javascript
{
    type: String,
    enum: ["day", "month", "year"]
}
```
Of course I understand that the String case can be achieved through the `match` validator, but String's aren't the only type of values that might benefit from this.
### Simple objects type shortcut
It would be nice to have a shortcut for non-compound types (i.e. everything but arrays and objects) such that instead of this:
```javascript
{
    p1: {type: String},
    p2: {type: Number}
}
```
I could write this:
```javascript
{
    p1: String,
    p2: Number
}
```
### Multiple custom validators
Sometimes due to code reusability I had to split the functions I wrote as custom validators; I guess you know more than I do that chaining async functions tangles up the code a lot and tends to be cumbersome. It would be nice to be able to specify a list of custom validators like so:
```javascript
{
    custom: [f1, f2, ...]
}
```

Thanks for all the effort you are putting into this library. I don't consider my JS-fu valuable enough as I'm using Node.js without much JS knowledge, or I'd sure try to implement these features myself!

**Comment by trenskow** [comment]
Hi again @mikidep 

Thank you so much for this! It is really cool, that you keep coming with all this good feedback - I can't imagine why I didn't think of the non-Object and Array shortcuts. :)

I will dig into these suggestions right away. It can't be soon enough before we got those implemented. All of them seem pretty reasonable, and should be pretty strait forward to implement.

Actually in regards to the enum suggestion, I did implement exactly what you suggest - with the same syntax - in version 0.3.3 (See https://github.com/trenskow/isvalid#enum). Although it is only available for strings, as numbers has the `range` validator, which also that kind of behaviour. Does it make sense to have enums on dates, booleans, objects and arrays? I don't think so - or can you imagine some cases, where this would come in useful?

The chainable custom validators should also be pretty easy to implement. I'll take a look at all of them later tonight, when I've gotten home from work.

Thank you again for your great feedback. It really a nice feeling, to know that other people are benefiting from what you made. :)

You'll hear from me, when I have something to show you - or if I need your feedback on something.

Talk to you soon...

**Comment by trenskow** [comment]
Features should be in master (not on npm, yet). ;)

**Comment by trenskow** [comment]
(See the README, also)

**Comment by trenskow** [comment]
Pushed to npm as v1.2.0.
