### ISSUE TITLE
Adding additional  data type (like String, Number, Array....) is not working

### ISSUE THREAD

**Issue by grunzmeniroj** [trenskow/isvalid#13]
Hello, trenskow
Thanks for the great library. But I want add some custom type in your library but I am getting  error ReferenceError: ...... is not defined when I try to use it after defining it.

I had added   this function in validate.js file

 var validateMongoId=function(mongoId, schema, fn, keyPath, options){
     var hexadecimal = /^[0-9A-F]+$/i;

     var mId = mongoId;

     if (hexadecimal.test(mId) && mId.length === 24) {
         return validateCustom(mId, schema, fn, keyPath, options);
     }
     else
     {
         return fn(
             new ValidationError(
                 keyPath,
                 schema._nonFormalizedSchema,
                 'type',
                 (schema.errors || {}).type || 'Is not of type MongoId.'
             )
         );
     }

 }//end of validateMongoId

and added this code in validateAny()

var validateAny = function(data, schema, fn, keyPath, options) {

	// If schema is not yet formalized - formalize it and come back.
	if (schema._nonFormalizedSchema === undefined) {
		return schemaTools.formalize(schema, function(formalizedSchema) {
			return validateAny(data, formalizedSchema, fn, keyPath, options);
		});
	}

	if (typeof data === 'undefined' || data === null) {
		if (data === null) {
			if (schema.allowNull === true || (options || {}).allowNull === true) {
				return validateCustom(data, schema, fn, keyPath, options);
			}
			return fn(
				new ValidationError(
					keyPath,
					schema._nonFormalizedSchema,
					'allowNull',
					(schema.errors || {}).allowNull || 'Cannot be null.'
				)
			);
		}
		if (typeof schema.default !== 'undefined') {
			if (typeof schema.default === 'function') {
				// If function has no arguments it is assumed sync.
				if (schema.default.length == 0) {
					return validateCustom(schema.default(), schema, fn, keyPath, options);
				} else {
					return schema.default(function(defaultValue) {
						validateCustom(defaultValue, schema, fn, keyPath, options);
					});
				}
			} else {
				// Else just apply default value.
				return validateCustom(schema.default, schema, fn, keyPath, options);
			}
		}
		if (schema.required === true || (options || {}).required === true) {
			return fn(
				new ValidationError(
					keyPath,
					schema._nonFormalizedSchema,
					'required',
					 (schema.errors || {}).required || 'Data is required.'
				 )
			 );
		} else {
			return validateCustom(data, schema, fn, keyPath, options);
		}
	}

	if (schema.type === undefined) return validateCustom(data, schema, fn, keyPath, options);
	if ('Object' == schema.type.name) return validateObject(data, schema, fn, keyPath, options);
	if ('Array' == schema.type.name) return validateArray(data, schema, fn, keyPath, options);
	if ('String' == schema.type.name) return validateString(data, schema, fn, keyPath, options);
	if ('Number' == schema.type.name) return validateNumber(data, schema, fn, keyPath, options);
	if ('Boolean' == schema.type.name) return validateBoolean(data, schema, fn, keyPath, options);
	if ('Date' == schema.type.name) return validateDate(data, schema, fn, keyPath, options);
    
        if ('MongoId'==schema.type.name) return validateMongoId(data, schema, fn, keyPath, options);

	// This error should have been eliminated by the finalizer.
	throw new Error('Cannot validate schema of type ' + schema.type.name + '.');

};

What I am missing please help

**Comment by brianreavis** [comment]
> ReferenceError: ...... is not defined

Why the dots? That's the most most important information.

Why not just use `custom` validator so you don't have to modify the library?
https://github.com/trenskow/isvalid#synchronous-example

*P.S: https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks*

**Comment by grunzmeniroj** [comment]
Thanks for your reply,  To night when I will reach home I will come back with full stack trace of the error, For now I am using custom validator but the example shown in my question is very simple and is used just for this example

**Comment by trenskow** [comment]
Why not just use the `{ type: String, match: /^[0-9A-F]+$/ }`?

**Comment by trenskow** [comment]
MongoId is not a JavaScript type, and I think thats why it's failing.
