### ISSUE TITLE
Validate array of objects

### ISSUE THREAD

**Issue by danielgil** [trenskow/isvalid#16]
Hi,
Thanks for this library, it's been really useful!

I think I've found an issue that might be worth investigating. While trying to validate an array of objects:
```
{somekey: [ {anotherkey: "value1"}, {anotherkey:"value2"}]}
```

With the following code:

```
router.post('/test', function (req, res){
    validate(req.body,{
        type: Object,
        schema: {
            'somekey': {
                type: Array,
                schema: {
                    type: Object,
                    schema: {
                        'anotherkey': {type: String}
                    }
                }
            }
        }
    }, function(err, validatedData){
    ...
    });
});
```

I get an unknown key error:
```
{"keyPath":["somekey","0","anotherkey"],"schema":{},"validator":"unknownKeys","message":"Unknown key."}
```
Is this supported? The tests in schema.js seem to imply that it is, but couldn't get it to work without some tinkering.

**Comment by trenskow** [comment]
`router` what is that? Are you using _express.js_?

**Comment by danielgil** [comment]
Yeah.  However I closed the issue as I found it was an error on my part.
