### ISSUE TITLE
how do i do size checking on String?

### ISSUE THREAD

**Issue by jlc488** [trenskow/isvalid#17]
if i have a string with max size limit.. how do i do that???

custom validator?

**Comment by trenskow** [comment]
I was actually - as in *today* - having the same issue. The `String` type needs a `len` validator - like the array.

But for now, you can use the `match` validator, together with a Regular Expression.

Example: `{ type: String, match: /^.{,100}$/ }

**Comment by erokshark** [comment]
Is this fixed already?

**Comment by trenskow** [comment]
@erokshark Yes, strings should support the `len` validator now. It uses the same syntax as the one on `Array`. I don't know if it is documented yet, but it is implemented, so feel free to use it.
