### ISSUE TITLE
Type String enum with default not working

### ISSUE THREAD

**Issue by DanielSuperSonic** [trenskow/isvalid#23]
When trying to put default value with enum on type String I get error:
> Possible values are 'full' and 'onlyActive'."

Request is without any values so i expect responseData to be 'full'
This is the configuration:
`responseData: {
    type: String,
    default: 'full',
    enum: ['full', 'onlyActive']
},`

This is not supported?

**Comment by trenskow** [comment]
This is a bug. It should definitely pass.
Thanks.
