### ISSUE TITLE
Feature request: remove unknown fields from the validated blob

### ISSUE THREAD

**Issue by boldt** [trenskow/isvalid#8]
Until now, you have `allowUnknownKeys`, which make sure that keys not intended in the data are passed through.

**This is a feature request**: 

Create an option `removeUnknownKeys`,  sucht that keys not intended in the data are dropped.

The idea comed from [Paperwork](https://github.com/lperrin/paperwork#changes-from-1x):

*Paperwork now silently removes unknown fields from the validated blob. This is done so you never pass unvalidated data to your code. For instance, if an attacker was to pass an extra id, you might end up using it to update the wrong object in your database.*

**Comment by trenskow** [comment]
Yes, that is a great idea. I will make this for the next version.

It might be, that I'm changing the `allowUnknownKeys` to an enum named `unknownKeys` with the possible values of `allow`, `deny`, `remove`.

**Comment by trenskow** [comment]
This is now in master: https://github.com/trenskow/isvalid#unknownkeys

**Comment by trenskow** [comment]
If you'd like, test it out, and I will publish it to npm.

**Comment by boldt** [comment]
Great! I will test it now :)

**Comment by trenskow** [comment]
+1

**Comment by trenskow** [comment]
:+1:

**Comment by boldt** [comment]
Can you give me a short example, how to integrate `unknownKeys` to the `validate.body`?

**Comment by trenskow** [comment]
Yes. One example could be.

    validate.body({
        type: Object,
        unknownKeys: 'remove',
        schema: {
            awesome: { type: Boolean }
        }
    })

Now this req.body:

    {
        awesome: true,
        why: 'It is!'
    }

Will become this:

    {
        awesome: true
    }

after validation.

Does that make sense? :)

**Comment by boldt** [comment]
This is a good example (please add is to the README as well).

The `unknownKeys: 'remove',` works perfect in my Angular app which was sending a lot more angular specific data within the JSON, shich is removed now.

**Comment by trenskow** [comment]
Perfect! Thank you!

The README really needs to be split up into multiple files. It is getting too comprehensive. But yes - I will add it. :+1: :)

**Comment by trenskow** [comment]
Done. ;)
https://github.com/trenskow/isvalid#unknownkeys
